
# Logging
logging:
  level:
    root: info
    com.netflix: debug

# Spring
spring:
  application:
    name: spring-cloud-ribbon

# Spring CLOUD RIBBON
### PLEASE NOTE: following configurations replace the ones in com.rabbit.samples.ribbon.ribbonclient.configs.RibbonConfig
### PLEASE NOTE: prefix is the name of the server the Ribbon client wants to communicate with
greeting-server:
  ribbon:
    eureka:
      enabled: false
    listOfServers: localhost:8081,localhost:8082
    ServerListRefreshInterval: 5000
    NFLoadBalancerPingClassName: com.netflix.loadbalancer.PingUrl
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.WeightedResponseTimeRule
